name: AAKAR 2025 Bug Report 🐛
description: File a bug report for the AAKAR 2025 Techno-Cultural Fest project.
title: "[Bug]: "
labels: ["bug", "Open Source", "AAKAR2025"]
assignees: ["Ajiet-AAKAR"]

body:
  - type: markdown
    attributes:
      value: |
        <h1 align="center">AAKAR 2025 - Techno-Cultural Fest of AJIET</h1>
        
        <p align="center">
          <img alt="GitHub pull-requests" src="https://img.shields.io/github/issues-pr/gaureshpai/aakar2025">
          <img alt="GitHub forks" src="https://img.shields.io/github/forks/gaureshpai/aakar2025">
          <img alt="contributors" src="https://img.shields.io/github/contributors/gaureshpai/aakar2025">
          <img alt="GitHub stars" src="https://img.shields.io/github/stars/gaureshpai/aakar2025">
        </p>
        
        Thanks for being part of **AAKAR 2025**! Please make sure to search existing issues before reporting a new bug.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search the existing issues to see if a similar bug has already been reported.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a detailed description of the issue you encountered.
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen instead.
      placeholder: Describe the expected behavior...

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: screenshots
    attributes:
      label: Add Screenshots
      description: Upload screenshots to help explain your problem.

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other

  - type: checkboxes
    id: roles
    attributes:
      label: Your Role in AAKAR 2025
      options:
        - label: "I'm an AAKAR Organizing Team Member"
          required: false
        - label: "I'm a Developer/Designer"
          required: false
        - label: "I want to work on this issue"
          required: false
        - label: "I'm willing to provide further clarification or assistance if needed."
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true

footer: |
  ### Need help?
  - Refer to [AAKAR 2025 Docs](https://github.com/gaureshpai/aakar2025)
  - Join the [AAKAR Community on Github](https://github.com/Ajiet-Devnation)